### ISSUE TITLE
[Feature request]: Notify the user in the status line if the opened file is read-only

### ISSUE THREAD

**Issue by HanatoK** [when-q/nvim-config#1]
Currently I don't see noticeable difference in the status line when opening read-only file. Is it possible to add an option to show a message(such as `[RO]`) in the status line if the file opened is read-only?

I am not familiar with Lua and neovim, but google leads me to https://github.com/nvim-lualine/lualine.nvim/pull/149/commits/a250a505f3f5c93bafb85dfac112e690d93a05e5#diff-3415e332dffb2dfeea02f2d64fbd437c960e1dec5fa99f701ad901a0d245bde4. It seems this can be implemented by using `vim.bo.readonly`.

**Comment by when-q** [comment]
Done. Modification is in `lua/theme/line.lua`.
